# Generated by Django 5.1.5 on 2025-01-29 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('rec_id', models.BigAutoField(editable=False, help_text='Record Id', primary_key=True, serialize=False)),
                ('E_ID', models.BigIntegerField(help_text='Employee ID', unique=True)),
                ('E_NAME', models.CharField(help_text='Employee Name', max_length=30)),
                ('E_BRANCH', models.CharField(help_text='Employee Branch', max_length=15)),
                ('E_DESIGNATION', models.CharField(help_text='Employee Designation', max_length=40)),
                ('E_ADDR', models.CharField(help_text='Employee Address', max_length=100)),
                ('E_CONT_NO', models.BigIntegerField(help_text='Employee Phone')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('rec_id', models.BigAutoField(editable=False, help_text='Record Id', primary_key=True, serialize=False)),
                ('M_ID', models.BigIntegerField(help_text='Membership Id', unique=True)),
                ('Start_date', models.DateField(blank=True, help_text='Membership Start Date', null=True)),
                ('End_date', models.DateField(blank=True, help_text='Membership End Date', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('rec_id', models.BigAutoField(editable=False, help_text='Record Id', primary_key=True, serialize=False)),
                ('SH_ID', models.BigIntegerField(help_text='Shipmet Id', unique=True)),
                ('Current_Status', models.CharField(help_text='Current Status of Shipment', max_length=15)),
                ('Sent_date', models.DateField(blank=True, help_text='Sent Date', null=True)),
                ('Delivery_date', models.DateField(blank=True, help_text='Delivery Date', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('rec_id', models.BigAutoField(editable=False, help_text='Record Id', primary_key=True, serialize=False)),
                ('C_ID', models.BigIntegerField(help_text='Customer Id', unique=True)),
                ('C_NAME', models.CharField(help_text='Customer Name', max_length=30)),
                ('C_EMAIL_ID', models.CharField(help_text='Customer Email', max_length=50)),
                ('C_CONT_NO', models.BigIntegerField(help_text='Customer Phone')),
                ('C_ADDR', models.CharField(help_text='Customer Address', max_length=100)),
                ('C_TYPE', models.CharField(help_text='Customer Type', max_length=30)),
                ('M_ID', models.ForeignKey(help_text='Customer Membership Id', on_delete=django.db.models.deletion.CASCADE, to='interview_app.membership')),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('rec_id', models.BigAutoField(editable=False, help_text='Record Id', primary_key=True, serialize=False)),
                ('SH_ID', models.BigIntegerField(help_text='Shipment Id', unique=True)),
                ('SH_CONTENT', models.CharField(help_text='Shipmet Content Type', max_length=40)),
                ('SH_DOMAIN', models.CharField(help_text='Shipment Domain', max_length=15)),
                ('SER_TYPE', models.CharField(help_text='Shipment Service Type', max_length=15)),
                ('SH_WEIGHT', models.CharField(help_text='Shipment Weight', max_length=10)),
                ('SH_CHARGES', models.IntegerField(help_text='Shipment Charges')),
                ('SR_ADDR', models.CharField(help_text='Source Address', max_length=100)),
                ('DS_ADDR', models.CharField(help_text='Destination Addres', max_length=100)),
                ('C_ID', models.ForeignKey(help_text='Customer Id', on_delete=django.db.models.deletion.CASCADE, to='interview_app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('rec_id', models.BigAutoField(editable=False, help_text='Record Id', primary_key=True, serialize=False)),
                ('Payment_ID', models.CharField(help_text='Payment Id (UID)', max_length=40)),
                ('AMOUNT', models.IntegerField(help_text='Customer Payment Amount')),
                ('Payment_Status', models.CharField(help_text='Payment Status', max_length=10)),
                ('Payment_Mode', models.CharField(help_text='Payment Method', max_length=25)),
                ('Payment_Date', models.DateField(blank=True, help_text='Payment Date', null=True)),
                ('C_ID', models.ForeignKey(help_text='Shipment Customer Id', on_delete=django.db.models.deletion.CASCADE, to='interview_app.customer')),
                ('SH_ID', models.ForeignKey(help_text='Shipment Id', on_delete=django.db.models.deletion.CASCADE, to='interview_app.shipment')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeManagesShipment',
            fields=[
                ('rec_id', models.BigAutoField(editable=False, help_text='Record Id', primary_key=True, serialize=False, unique=True)),
                ('Employee_E_ID', models.ForeignKey(help_text='Employee Id', on_delete=django.db.models.deletion.CASCADE, to='interview_app.employee')),
                ('Shipment_Sh_ID', models.ForeignKey(help_text='Shipment Id', on_delete=django.db.models.deletion.CASCADE, to='interview_app.shipment')),
                ('Status_Sh_ID', models.ForeignKey(help_text='Shipment Status', on_delete=django.db.models.deletion.CASCADE, to='interview_app.status')),
            ],
        ),
    ]
